/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Interactive balance data with accounts, journal entries and the balance sheet structure
 */
export interface InteractiveBalanceData {
  balanceSheet: BalanceSheet;
  /**
   * List of all accounts
   */
  accounts: Account[];
  /**
   * List of all journal Entries
   */
  journalEntries: JournalEntry[];
}
/**
 * The balance sheet holding the structure of accounts, sums and balance
 */
export interface BalanceSheet {
  /**
   * List of all positions and accounts on the assets side
   */
  assets: Position[];
  /**
   * List of all positions and accounts on the liabilities and equity side
   */
  liabilitiesAndEquity: Position[];
}
export interface Position {
  label: string;
  /**
   * List of account ids directly assigned to this position
   */
  accounts: string[];
  positions: Position[];
}
/**
 * Account in the balance sheet
 */
export interface Account {
  id: string;
  label: string;
}
/**
 * A journal entry with at least one debit-line and one credit-line
 */
export interface JournalEntry {
  id: string;
  entryLines: EntryLine[];
}
export interface EntryLine {
  accountId: string;
  amount: number;
  entryType: "credit" | "debit";
}
